language: java
jdk:
  - openjdk8
##before_install:
##  - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar && java -jar BuildTools.jar --rev 1.12.2
notifications:
  email: false

